### ISSUE TITLE
Gold chests display the wrong values

### ISSUE THREAD

**Issue by Entroper** [Entroper/Randomizers#12]
When prices are scaled, the amount of gold in each gold chest is scaled, but the text doesn't change.  The text is well packed, so it's difficult to change because it could move lots of other text.  We need a comprehensive text packing system to fix this.

**Comment by thecubemiser** [comment]
An alternative fix is to not scale chests?

**Comment by Entroper** [comment]
Done in 0.9.2 (chests aren't scaled).
