### ISSUE TITLE
Confused enemies cast weird spells

### ISSUE THREAD

**Issue by Entroper** [Entroper/Randomizers#13]
Apparently, in the original game, confused enemies cast the FIRE spell on each other.  Now, they cast whatever spell gets shuffled there.  This doesn't affect the game much, it's more amusing than anything, but it probably ought to be fixed.

**Comment by thecubemiser** [comment]
I saw/heard someone say in a chat or stream that they end up casting the first spell in the spell list (which happens to be FIRE)

**Comment by Entroper** [comment]
Fixed in 0.9.4.
