### ISSUE TITLE
FF1 Randomizer

### ISSUE THREAD

**Issue by Entroper** [Entroper/Randomizers#2]
Reference: http://www.gamefaqs.com/nes/522595-final-fantasy/faqs/57009

- [x] Treasures -- need sanity checks
  * CROWN not behind mystic key door
  * TNT accessible in Coneria/Elfland/Pravoka area
  * RUBY not in lower Earth Cave
  * FLOATER accessible in southern hemisphere
  * SLAB before Mirage Tower
- [x] We'd like to place the quest items as permissively as possible, so we need a system that detects circular dependencies.  Like the CROWN being in the northern hemisphere and the FLOATER being behind a mystic key door.
- [x] Shops
  * Bottle needs sanity checks  
    **EDIT:** Surprisingly, it doesn't, mainly because Lefein doesn't have an item shop.
- [x] Magic levels, i.e. NUKE can become an L1 spell if it's shuffled to the L1 shop
- [x] Enemy skills/spells
- [x] Enemy status attacks (e.g. stun, death)

The following would be not shuffled, but scaled by a random exponential factor:
- [x] Prices
- [x] Enemy stats (HP, damage, hits, accuracy, critical, defense, evade, magic defense, morale)

**Comment by abyssonym** [comment]
Suggestion: Randomize enemy stats (each individually) to a value between their original value and the scaled value. This would result in an experience that is more textured and varied, having the potential to surprise the player and encourage adaptation, without having the severe balance issues of a straight-up shuffle. Naturally, it would introduce another luck component to the randomizer, though.

**Comment by thecubemiser** [comment]
RE: Floater location -

The floater should be accessible inside of the Castle of Ordeals, since it is accessible by ship.

**Comment by Entroper** [comment]
@thecubemiser It is actually.  And I'm probably going to change the placement system soon.  Quest items are always tending to end up in the same place.

**Comment by abyssonym** [comment]
I did a simulation of your Scale algorithm, using 10 as the unscaled value and 2.0 as the scale, and I think this might explain why people think the stat scaling is too easy. Is this the sort of probability curve you were looking for? There's an equal number of lesser and greater values, but lower values are favored on both sides of the randomization.
![figure_1](https://cloud.githubusercontent.com/assets/8162987/18011399/d86f1ec8-6b69-11e6-97a1-5c66f9a8804a.gif)

**Comment by Entroper** [comment]
@abyssonym Yeah, that's the curve I wanted.  The exponential distribution has the same average as the middle value, where the exponent is zero.

I'll be adjusting this in the near future.  I may not even use the same curve for each stat, because some are much more important than others.

**Comment by abyssonym** [comment]
I think the exponential distribution could be interesting if it was mirrored, so that +50% of the original value is the maximum and -100% is the minimum, with +50% being significantly more common than +0% or -50%. I've been using a triangular distribution for basically everything in my randomizers, though until just now I'd thought it was a normal distribution.

**Comment by Jaylow7** [comment]
Not sure if the logic already prevents this, but the CROWN can not be in Castle of Ordeals, as it is required to enter.

**Comment by Entroper** [comment]
@Jaylow7 Yeah, I added that as part of the sanity checks a while back.  The ToFR check is separate from the rest because it's a bit faster to do it that way.

**Comment by thecubemiser** [comment]
RE: Enemy statistics - I would expect the distribution pattern to look like a bell curve centered on the original value. Is this not the case right now?

It would probably work even better as a bell that has a shorter low-end and longer high-end, but with equal numbers of higher/lower values across tons of iterations. I.e. with base 100, values range from 75 to 150.

**Comment by thecubemiser** [comment]
![image](https://cloud.githubusercontent.com/assets/21252852/18030900/4b08a8b8-6c97-11e6-8a6b-ae3990fef2c3.png)

Here's what I was thinking.

**Comment by Entroper** [comment]
All 1.0 features are implemented.
