### ISSUE TITLE
Quality of Life issue (Soft Potions)

### ISSUE THREAD

**Issue by Jaylow7** [Entroper/Randomizers#20]
Is it possible to add a check that will ensure SOFT potions are available somewhere in the south half of the map? I was just part of a race where I lost 45 minutes (and eventually forfeit) due to lack of SOFT potions and a common enemy in Earth cave having petrify effect on their attacks. In this specific case it was Gargoyles, but it can be an issue even without status attack shuffle due to Coctrice.

**Comment by Entroper** [comment]
Yeah, this is a good idea.  CLINIC won't heal stone, right?  So you're 100% screwed if anyone gets petrified.

**Comment by Jaylow7** [comment]
Correct. The only way to cure Stone status is a SOFT potion or spell.

**Comment by Entroper** [comment]
Done for 1.0.
