### ISSUE TITLE
Bad seed?

### ISSUE THREAD

**Issue by gameboy9** [Entroper/Randomizers#21]
I couldn't find the crown, so I couldn't find the key -> cube -> rattail -> etc.  I looked everywhere that I could think of.  Seed 3C4D6E25, flags TSMLpAROFoo

Thanks for looking into this!

**Comment by Entroper** [comment]
Isn't the CUBE at the waterfall?  The robot gives it to you.

I checked your seed, the CROWN is in the Sky Palace, so you do need the CUBE to get it.  But you should be able to get the CUBE.
