### ISSUE TITLE
FF1 Conveniences (1.0)

### ISSUE THREAD

**Issue by Entroper** [Entroper/Randomizers#22]
- [x] Don't shuffle party after poison/stone/death
- [x] Allow obtaining the ROD from Sarda before killing the VAMPIRE
- [x] Allow obtaining the CANOE from Lukahn before killing LICH

**Comment by Entroper** [comment]
Early Canoe requires a rewrite of treasure sanity checks.  Enqueue all chests you can access with nothing, keep dequeuing, and enqueue more chests when you dequeue a quest item.  Continue until the queue is empty (reshuffle chests) or all treasures are accounted for (proceed).

**Comment by jkoper** [comment]
Just something to think about:  I assume that you might need to reorder the party if the first member is stoned or dies, or else the game might crash.  (If not, then no worries.)  For all other deaths, I'd prefer the party not be shuffled.

**Comment by Entroper** [comment]
I think you can manually shuffle dead or stoned members to the top, and it doesn't crash.  I'll test it, though.

**Comment by Jaylow7** [comment]
I know the game will not let you have a dead person in the 1st position, you can _not_ manually swap a dead person to that spot. Stoned I believe is fine.

**Comment by Entroper** [comment]
Disabled party shuffling in 0.8.1.

**Comment by Entroper** [comment]
Early Canoe is in 0.9.0.
