### ISSUE TITLE
CHAOS can be literally impossible to kill

### ISSUE THREAD

**Issue by Entroper** [Entroper/Randomizers#23]
Watched czardia playing last night, and he got a max-evade CHAOS with lots of HP.  Hit him with lots of low-level NUKE and FADE spells, was missing all day with FASTed Knight+Masmune and Master, could not defeat him between casts of CUR4 despite racking up over 5000 damage.

I like some enemies having sky-high evade, even if it's super inconvenient, like AIR (unrunnable).  But it does break the game if it happens to CHAOS along with really high HP.  Should probably clamp enemy agility slightly lower than 255.

**Comment by hellool** [comment]
With the new flags in 0.8 it's my understanding that a boss could have a script to, for example, cast only CUR4 (or something like RUSE and CUR4) with a high probability, making it impossible or nearly impossible to defeat. While I've yet to actually encounter a game breaking script like this it seems reasonably likely to happen in some seeds. Do you have plans to add additional checks for such things? Or are certain seeds with shuffle spells/scripts flags just expected to be like this?

**Comment by Entroper** [comment]
Yeah, we had talked about the CUR4 issue on Twitch possibly breaking the game.  However, I looked into it a bit more, and it won't be a problem because all of the bosses have full spell lists.  So there's no chance for any of them to get fewer than 8 spells (unless they get no spells at all, since WarMECH doesn't have any).

**Comment by Entroper** [comment]
Clamped evade to 250 in 0.8.1.
