### ISSUE TITLE
Step Counter, Encounter Table

### ISSUE THREAD

**Issue by jkoper** [Entroper/Randomizers#25]
I would like to see both the step counter and the encounter table shuffled and/or randomized as options.  As things currently stand, there is an inherent advantage in racing the randomizer for people who know how to manipulate the step counter and get the fights that they want.  I know some people have used the encounter table to avoid certain dangerous fights, and, though I haven't gotten to that point yet, there's a good chance I will soon.  I'd like to just play the game without knowing exactly what's coming myself, to avoid having to follow every detail, so I'd prefer that the encounter tables and step counter just be shuffled or randomized in some fashion, at least as an option.

**Comment by Entroper** [comment]
This is a really neat idea.  I think I can just shuffle the RNG table.  All the probabilities would be the same, but in a different order.

**Comment by Entroper** [comment]
Done in 0.9.2.
