### ISSUE TITLE
Magic shuffle issue

### ISSUE THREAD

**Issue by Jaylow7** [Entroper/Randomizers#6]
I have encountered a bug where moving spells around is also affecting the spells used by the various spellcasting items.

In the case I encountered, the Heal Staff is attempting to cast MUTE.

Here's a video showing the issue:
https://www.dropbox.com/s/kkpkfw6nosklvcw/FF1RandoBug.mp4?dl=0

**Comment by Jaylow7** [comment]
This was on the latest release, 0.4.2
Seed D1E9CC70

Settings:
Shuffle Treasures
Shuffle Shops
Shuffle Magic Levels
Exp/Gold Boost 5x+0

**Comment by Entroper** [comment]
Thanks for the report.  This should be an easy fix for 0.4.3.

**Comment by Entroper** [comment]
Fixed in 0.4.3.
