### ISSUE TITLE
0.5.3 Issue with Spell Permissions.

### ISSUE THREAD

**Issue by EunosXX** [Entroper/Randomizers#9]
I'm not actually certain about the intented behavior for changing Spell Permissions, but I didn't expect it to behave the way it did. In a seed with unshuffled magic shops and unrestricted magic (TSmLp), spell permissions were being granted to classes based on the position of the spell in the shop.

E.G. The White Magic shop in Melmond (L5).
Original Spells in order: CUR3 LIFE HRM3 HEL2
Shuffled Spells in order: PURE HRM3 FOG HEL2

So for my Red Mage, PURE was learnable unpromoted as CUR3 would have been, and HRM3 was learned as a Red Wizard as LIFE would have been. Neither RM or RW could ever learn FOG or HEL2, as RW cannot originally learn HRM3 or HEL2. 

Further examples of spells I'd never expect the Red Mage to learn, but did: CUR4, HRM4, NUKE, BANE.
I wrote down every spell's permissions from the seed for white and red mage and wizard.  
https://docs.google.com/spreadsheets/d/1L4UVlVzio__3q4GD9s6615ArbEkiOHkVFdl0lp8wVoE/

**Comment by Entroper** [comment]
Yep, this was the way it was intended to work.  Basically, either the permissions move with the spells, so you can always learn the same spells (but they might be at different levels), OR the permissions stay put while the spells move around.  So you can always learn the same number of white and black spells, and at the same level, but which spells they are is up to the RNG.

I appreciate the report though.  :)  I'll try to be a bit clearer in the release notes and also update the README.
